version: "3.9"

services:
  frontend:
    image: genoyves/nexclinic-front:latest
    container_name: nexxclinic-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      API_BASE_URL: http://backend:8080
      SUPABASE_INTERNAL_URL: http://host.docker.internal:55321
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
