// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account" | "/admin" | "/admin/clinic-profile" | "/admin/departments" | "/admin/formbuilder" | "/admin/formbuilder/answer" | "/admin/formbuilder/edit" | "/admin/forms" | "/admin/insurances" | "/admin/products" | "/admin/users" | "/auth" | "/auth/setup-password" | "/billing" | "/consultation" | "/create-password" | "/register" | "/triage" | "/ward"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]" | "/graphql" | "/storage/sign/[[...path]]" | "/supa/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/account": {}
  "/admin": {}
  "/admin/clinic-profile": {}
  "/admin/departments": {}
  "/admin/formbuilder": {}
  "/admin/formbuilder/answer": {}
  "/admin/formbuilder/edit": {}
  "/admin/forms": {}
  "/admin/insurances": {}
  "/admin/products": {}
  "/admin/users": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/auth": {}
  "/auth/setup-password": {}
  "/billing": {}
  "/consultation": {}
  "/create-password": {}
  "/graphql": {}
  "/register": {}
  "/storage/sign/[[...path]]": { "path"?: string[]; }
  "/supa/[[...path]]": { "path"?: string[]; }
  "/triage": {}
  "/ward": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
