export const COUNTRIES = [
  "Rwanda",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
]

export interface RwandaSectors {
  [district: string]: string[]
}

export interface RwandaDistricts {
  [province: string]: RwandaSectors
}

export const RWANDA_PROVINCES = [
  "Kigali City",
  "Eastern Province",
  "Northern Province",
  "Southern Province",
  "Western Province",
] as const

export type RwandaProvince = (typeof RWANDA_PROVINCES)[number]

export const RWANDA_DATA: RwandaDistricts = {
  "Eastern Province": {
    Bugesera: [
      "Gashora", "Juru", "Kamabuye", "Mareba", "Mayange",
      "Musenyi", "Mwogo", "Ngeruka", "Ntarama", "Nyamata",
      "Nyarugenge", "Rilima", "Ruhuha", "Rweru", "Shyara",
    ],
    Gatsibo: [
      "Gasange", "Gatsibo", "Gitoki", "Kabarore", "Kageyo",
      "Kiramuruzi", "Kiziguro", "Muhura", "Murambi", "Ngarama",
      "Nyagihanga", "Remera", "Rugarama", "Rwimbogo",
    ],
    Kayonza: [
      "Gahini", "Kabare", "Kabarondo", "Mukarange", "Murama",
      "Murundi", "Mwiri", "Ndego", "Nyamirama", "Rukara",
      "Ruramira", "Rwinkwavu",
    ],
    Kirehe: [
      "Gahara", "Gatore", "Kigarama", "Kigina", "Kirehe",
      "Mahama", "Mpanga", "Musaza", "Mushikiri", "Nasho",
      "Nyamugari", "Nyarubuye",
    ],
    Ngoma: [
      "Gashanda", "Jarama", "Karembo", "Kazo", "Kibungo",
      "Mugesera", "Murama", "Mutenderi", "Remera", "Rukira",
      "Rukumberi", "Rurenge", "Sake", "Zaza",
    ],
    Nyagatare: [
      "Gatunda", "Karama", "Karangazi", "Katabagemu", "Kiyombe",
      "Matimba", "Mimuri", "Mukama", "Musheri", "Nyagatare",
      "Rukomo", "Rwempasha", "Rwimiyaga", "Tabagwe",
    ],
    Rwamagana: [
      "Fumbwe", "Gahengeri", "Gishali", "Karenge", "Kigabiro",
      "Muhazi", "Munyaga", "Munyiginya", "Musha", "Muyumbu",
      "Mwulire", "Nyakaliro", "Nzige", "Rubona",
    ],
  },
  "Kigali City": {
    Gasabo: [
      "Bumbogo", "Gatsata", "Gikomero", "Gisozi", "Jabana",
      "Jali", "Kacyiru", "Kimihurura", "Kimiromko", "Kinyinya",
      "Ndera", "Nduba", "Remera", "Rusororo", "Rutunga",
    ],
    Kicukiro: [
      "Gahanga", "Gatenga", "Gikondo", "Kagarama", "Kanombe",
      "Kicukiro", "Kigarama", "Masaka", "Niboye", "Nyarugunga",
    ],
    Nyarugenge: [
      "Gitega", "Kanyinya", "Kigali", "Kimisagara", "Mageragere",
      "Muhima", "Nyakabanda", "Nyamirambo", "Nyarugenge", "Rwezamenyo",
    ],
  },
  "Northern Province": {
    Burera: [
      "Bungwe", "Butaro", "Cyanika", "Cyeru", "Gahunga",
      "Gatebe", "Gitovu", "Kagogo", "Kinoni", "Kinyababa",
      "Kivuye", "Nemba", "Rugarama", "Rugengabari", "Ruhunde",
      "Rusarabuye", "Rwerere",
    ],
    Gakenke: [
      "Busengo", "Coko", "Cyabingo", "Gakenke", "Gashenyi",
      "Janja", "Kamubuga", "Karambo", "Kivuruga", "Mataba",
      "Minazi", "Mugunga", "Muhondo", "Muyongwe", "Muzo",
      "Nemba", "Ruli", "Rusasa", "Rushashi",
    ],
    Gicumbi: [
      "Bukure", "Bwisige", "Byumba", "Cyumba", "Giti",
      "Kageyo", "Kaniga", "Manyagiro", "Miyove", "Mukarange",
      "Muko", "Mutete", "Nyamiyaga", "Nyankenke", "Rubaya",
      "Rukomo", "Rushaki", "Rutare", "Ruvune", "Rwamiko",
      "Shangasha",
    ],
    Musanze: [
      "Busogo", "Cyuve", "Gacaca", "Gashaki", "Gataraga",
      "Kimonyi", "Kinigi", "Muhoza", "Muko", "Musanze",
      "Nkotsi", "Nyange", "Remera", "Rwaza", "Shingiro",
    ],
    Rulindo: [
      "Base", "Burega", "Bushoki", "Buyoga", "Cyinzuzi",
      "Cyungo", "Kinihira", "Kisaro", "Masoro", "Mbogo",
      "Murambi", "Ngoma", "Ntarabana", "Rukozo", "Rusiga",
      "Shyorongi", "Tumba",
    ],
  },
  "Southern Province": {
    Gisagara: [
      "Gikonko", "Gishubi", "Kansi", "Kibirizi", "Kigembe",
      "Mamba", "Muganza", "Mugombwa", "Mukingo", "Musha",
      "Ndora", "Nyanza", "Save",
    ],
    Huye: [
      "Gishamvu", "Huye", "Karama", "Kigoma", "Kinazi",
      "Maraba", "Mbazi", "Mukura", "Ngoma", "Ruhashya",
      "Rusatira", "Rwaniro", "Simbi", "Tumba",
    ],
    Kamonyi: [
      "Gacurabwenge", "Karama", "Kayenzi", "Kayumbu", "Mugina",
      "Musambira", "Ngamba", "Nyamiyaga", "Nyarubaka", "Rugarika",
      "Rukoma", "Runda",
    ],
    Muhanga: [
      "Cyeza", "Kabacuzi", "Kibangu", "Kiyumba", "Muhanga",
      "Mushishiro", "Nyabinoni", "Nyamabuye", "Nyarusange",
      "Rongi", "Rugendabari", "Shyogwe",
    ],
    Nyamagabe: [
      "Buruhukiro", "Cyanika", "Gasaka", "Gatare", "Kaduha",
      "Kamegeri", "Kibirizi", "Kibumbwe", "Kitabi", "Mbazi",
      "Mugano", "Musange", "Musebeya", "Mushubi", "Nkomane",
      "Tare", "Uwinkingi",
    ],
    Nyanza: [
      "Busasamana", "Busoro", "Cyabakamyi", "Kibirizi", "Kigoma",
      "Mukingo", "Muyira", "Ntyazo", "Nyagisozi", "Rwabicuma",
    ],
    Nyaruguru: [
      "Busanze", "Cyahinda", "Kibeho", "Kivu", "Mata",
      "Muganza", "Munini", "Ngera", "Ngoma", "Nyabimata",
      "Nyagisozi", "Ruheru", "Ruramba", "Rusenge",
    ],
    Ruhango: [
      "Bweramana", "Byimana", "Kabagali", "Kinazi", "Kinihira",
      "Mbuye", "Mwendo", "Ntongwe", "Ruhango",
    ],
  },
  "Western Province": {
    Karongi: [
      "Bwishyura", "Gishari", "Gishyita", "Gitesi", "Mubuga",
      "Murambi", "Murundi", "Mutuntu", "Rubengera", "Rugabano",
      "Ruganda", "Rwankuba", "Twumba",
    ],
    Ngororero: [
      "Bwira", "Gatumba", "Hindiro", "Kabaya", "Kageyo",
      "Kavumu", "Matyazo", "Muhanda", "Muhororo", "Ndaro",
      "Ngororero", "Nyange", "Sovu",
    ],
    Nyabihu: [
      "Bigogwe", "Jenda", "Jomba", "Kabatwa", "Karago",
      "Kintobo", "Mukamira", "Muringa", "Rambura", "Rugera",
      "Rurembo", "Shyira",
    ],
    Nyamasheke: [
      "Bushekeri", "Bushenge", "Cyato", "Gihombo", "Kagano",
      "Kanjongo", "Karambi", "Karengera", "Kirimbi", "Macuba",
      "Mahembe", "Nyabitekeri", "Rangiro", "Ruharambuga", "Shangi",
    ],
    Rubavu: [
      "Bugeshi", "Busasamana", "Cyanzarwe", "Gisenyi", "Kanama",
      "Kanzenze", "Mudende", "Nyakiriba", "Nyamyumba", "Nyundo",
      "Rubavu", "Rugerero",
    ],
    Rusizi: [
      "Bugarama", "Butare", "Bweyeye", "Gashonga", "Giheke",
      "Gihundwe", "Gikundamvura", "Gitambi", "Kamembe", "Muganza",
      "Mururu", "Nkanka", "Nkombo", "Nkungu", "Nyakabuye",
      "Nyakarenzo", "Nzahaha", "Rwimbogo",
    ],
    Rutsiro: [
      "Boneza", "Gihango", "Kigeyo", "Kivumu", "Manihira",
      "Mukura", "Murunda", "Musasa", "Mushonyi", "Mushubati",
      "Nyabirasi", "Ruhango", "Rusebeya",
    ],
  },
}

export const RWANDA_DISTRICTS = Object.keys(RWANDA_DATA)

export function getRwandaDistricts(province: string): string[] {
  const districts = RWANDA_DATA[province]
  return districts ? Object.keys(districts) : []
}

export function getRwandaSectors(province: string, district: string): string[] {
  const districts = RWANDA_DATA[province]
  if (!districts) return []
  return districts[district] || []
}

export function isRwandaSelected(country: string | null | undefined): boolean {
  return country?.toLowerCase() === "rwanda"
}
