import type { Patient, Consultation } from "./types"

const generateMockConsultations = (patientId: string): Consultation[] => [
  {
    id: `cons-${patientId}-1`,
    patientId,
    doctorId: "doc-001",
    date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    status: "completed",
    chiefComplaint: "Routine eye checkup",
    history: "No significant ocular history. Last glasses prescription 2 years ago.",
    vitalSigns: {
      bloodPressure: "120/80",
      heartRate: 72,
      temperature: 37.0,
      oxygenSaturation: 98,
      respiratoryRate: 16,
    },
    examinationFindings: {
      visualAcuityOD: "20/20",
      visualAcuityOS: "20/25",
      pupillaryReaction: "PERRL",
      extraocularMovements: "Full in all gazes",
      intraocularPressure: "OD: 15 mmHg, OS: 16 mmHg",
      anteriorSegment: "Clear cornea and lens",
      posteriorSegment: "Healthy optic disc, macula appears normal",
      otherFindings: "Mild presbyopia",
    },
    diagnosis: "Refractive error - Mild myopia OS, Age-related presbyopia",
    prescriptions: [
      {
        id: "presc-1",
        type: "glasses",
        glassesType: "Reading glasses",
        sphericalOD: "+0.50",
        sphericalOS: "+1.00",
        cylindricalOD: "-0.25",
        cylindricalOS: "-0.50",
        axisOD: "180",
        axisOS: "175",
        notes: "For reading and computer work",
      },
      {
        id: "presc-2",
        type: "appointment",
        appointmentDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
        appointmentReason: "Annual follow-up",
      },
    ],
    notes: "Patient doing well. Continue current eye care routine.",
  },
  {
    id: `cons-${patientId}-2`,
    patientId,
    doctorId: "doc-001",
    date: new Date().toISOString().split("T")[0],
    status: "pending",
    chiefComplaint: "",
    history: "",
    vitalSigns: {
      bloodPressure: "",
      heartRate: 0,
      temperature: 0,
      oxygenSaturation: 0,
      respiratoryRate: 0,
    },
    examinationFindings: {
      visualAcuityOD: "",
      visualAcuityOS: "",
      pupillaryReaction: "",
      extraocularMovements: "",
      intraocularPressure: "",
      anteriorSegment: "",
      posteriorSegment: "",
      otherFindings: "",
    },
    diagnosis: "",
    prescriptions: [],
    notes: "",
  },
]

export const mockPatients: Patient[] = [
  {
    id: "pat-001",
    name: "Sarah Johnson",
    age: 34,
    gender: "F",
    email: "sarah.johnson@email.com",
    phone: "+1-555-0101",
    medicalHistory: "No significant ocular history. Occasional dry eyes in winter.",
    lastVisit: new Date().toISOString().split("T")[0],
    consultations: generateMockConsultations("pat-001"),
  },
  {
    id: "pat-002",
    name: "Michael Chen",
    age: 52,
    gender: "M",
    email: "m.chen@email.com",
    phone: "+1-555-0102",
    medicalHistory: "Diabetic retinopathy risk. Family history of glaucoma.",
    lastVisit: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    consultations: generateMockConsultations("pat-002"),
  },
  {
    id: "pat-003",
    name: "Emily Rodriguez",
    age: 28,
    gender: "F",
    email: "emily.r@email.com",
    phone: "+1-555-0103",
    medicalHistory: "Myopic astigmatism. Uses contact lenses.",
    lastVisit: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    consultations: generateMockConsultations("pat-003"),
  },
  {
    id: "pat-004",
    name: "James Wilson",
    age: 65,
    gender: "M",
    email: "j.wilson@email.com",
    phone: "+1-555-0104",
    medicalHistory: "Cataracts in early stages. Hypertension controlled.",
    lastVisit: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    consultations: generateMockConsultations("pat-004"),
  },
  {
    id: "pat-005",
    name: "Lisa Park",
    age: 41,
    gender: "F",
    email: "lisa.park@email.com",
    phone: "+1-555-0105",
    medicalHistory: "Keratoconus. Uses specialty contact lenses.",
    lastVisit: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    consultations: generateMockConsultations("pat-005"),
  },
]

export const mockDoctor = {
  id: "doc-001",
  name: "Dr. Alexander Harrison",
  email: "dr.harrison@eyecare.com",
  phoneNumber: "+1234567890",
  title: "Ophthalmologist",
  roles: ["doctor"],
  active: true,
}
