// Compatibility layer - re-export everything from the new modular structure
export * from './types'
export * from './auth'
export * from './departments'
export * from './visits'
export * from './patients'
export * from './insurances'
export * from './billing'
export * from './forms'
export * from './products'
